info:
  app:
    name: @project.name@
    groupId: @project.groupId@
    artifactId: @project.artifactId@
    version: @project.version@
management:
  security:
    roles: ADMIN
spring:
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.HSQLDialect
    database: HSQL
  datasource:
    driverClassName: org.hsqldb.jdbcDriver
    url: jdbc:hsqldb:mem:auth
    username: sa
